#!/usr/bin/env python3
"""Generate the port's microarch/target-feature data layer FROM src/build_settings_microarch.cpp.

WHY THIS EXISTS (#612). The port used to hand-maintain this data and it drifted, twice, in ways no gate
here could see:

  1. microarch_default_features was a flat `switch microarch` with four arms, so `generic` returned the
     x86-64 feature list on wasm, arm32, arm64 and riscv64 alike. C++ indexes a PER-ARCH table: an arch
     offset via target_microarch_counts[], then a name match WITHIN that arch's slice only.
  2. target_features_list -- the validation table behind -target-features and @(enable_target_feature) --
     was stale against LLVM 22 on all seven real arches, in BOTH directions: 34 arm64 and 55 riscv64
     features the port rejected and C++ accepts, plus `tme`/`zcz`/`nacl-trap`/`amx-transpose` the port
     accepted and C++ rejects.

Hand-copying a 205 KB generated table is the defect, not the symptom. So: derive it.

WHY FROM THE C++ FILE AND NOT FROM LLVM. C++'s own table is generated by misc/featuregen/featuregen.py,
which queries LLVM. Regenerating from LLVM independently would let the port and the ORACLE disagree
whenever the checked-in C++ table lags the installed LLVM. Parity compares the port against the oracle
binary, so the oracle's compiled-in table is the thing we must agree with -- and that is exactly what
src/build_settings_microarch.cpp contains.

THE VERSION CAVEAT, STATED RATHER THAN HIDDEN. That C++ file holds FOUR tables behind
`#if LLVM_VERSION_MAJOR >= 22 / == 21 / == 20 / #else`, and the feature sets genuinely differ between them
(arm64 has 98/91/82/69 microarchs respectively). The port has no LLVM dependency and therefore no way to
know which one the oracle was compiled with. This script picks the block by --llvm-major (default: probe
llvm-config) and STAMPS the choice into the generated file as MICROARCH_LLVM_MAJOR, so a reader can see
which assumption the port is carrying. If the oracle is ever rebuilt against a different LLVM, this must be
re-run; the stamp is what makes that detectable instead of silent.

Usage:
    python3 .claude/tools/gen_microarch.py [--llvm-major N] [--check] [-o PATH]

    --check  parse and report, write nothing (use in a gate: exits 1 if the generated file is stale)
"""

import argparse
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
CPP = os.path.join(REPO, "src", "build_settings_microarch.cpp")
OUT = os.path.join(REPO, "core", "odin", "checker", "build_settings_microarch.odin")

# Must match Target_Arch_Kind in core/odin/checker/build_settings.odin AND TargetArchKind in
# src/build_settings.cpp. Both are (Invalid, amd64, i386, arm32, arm64, wasm32, wasm64p32, riscv64) and
# the generator ASSERTS that count below rather than trusting this list.
ARCHS = ["Invalid", "Amd64", "I386", "Arm32", "Arm64", "Wasm32", "Wasm64p32", "Riscv64"]


def detect_llvm_major():
    try:
        v = subprocess.run(["llvm-config", "--version"], capture_output=True, text=True, timeout=10)
        if v.returncode == 0:
            return int(v.stdout.strip().split(".")[0])
    except Exception:
        pass
    return None


def select_block(text, major):
    """Return the source text of the #if branch that a C++ build with this LLVM major would compile.

    The guards are, in file order: >= 22, == 21, == 20, #else. Anything below 20 takes the #else.
    """
    lines = text.split("\n")
    marks = []  # (line_index, kind)
    for i, ln in enumerate(lines):
        s = ln.strip()
        if re.match(r"^#if\s+LLVM_VERSION_MAJOR\s*>=\s*22", s):
            marks.append((i, ">=22"))
        elif re.match(r"^#elif\s+LLVM_VERSION_MAJOR\s*==\s*21", s):
            marks.append((i, "==21"))
        elif re.match(r"^#elif\s+LLVM_VERSION_MAJOR\s*==\s*20", s):
            marks.append((i, "==20"))
        elif s == "#else":
            marks.append((i, "else"))
        elif s == "#endif":
            marks.append((i, "endif"))
    # The file opens with an `#ifndef LLVM_VERSION_MAJOR / #error / #endif` sanity guard, whose #endif
    # would otherwise be counted as part of the version chain. Drop everything before the first version
    # branch rather than relaxing the count check -- the count is what would catch a real restructure.
    first = next((i for i, (_, k) in enumerate(marks) if k == ">=22"), None)
    if first is None:
        raise SystemExit("gen_microarch: no `#if LLVM_VERSION_MAJOR >= 22` branch in %s" % CPP)
    marks = marks[first:]
    if len(marks) != 5:
        raise SystemExit("gen_microarch: expected 5 preprocessor marks in the version chain of %s, found "
                         "%d -- the file's structure changed and this parser must be re-read, not "
                         "patched blindly" % (CPP, len(marks)))
    want = ">=22" if major >= 22 else ("==21" if major == 21 else ("==20" if major == 20 else "else"))
    for idx, (line_no, kind) in enumerate(marks):
        if kind == want:
            start = line_no + 1
            end = marks[idx + 1][0]
            return "\n".join(lines[start:end]), want
    raise SystemExit("gen_microarch: no block for %s" % want)


def unescape_c(s):
    return s.replace('\\"', '"').replace("\\\\", "\\")


def parse_string_array(name, blk):
    m = re.search(r"gb_global String " + name + r"\[TargetArch_COUNT\]\s*=\s*\{(.*?)\n\};", blk, re.S)
    if not m:
        raise SystemExit("gen_microarch: %s not found in the selected block" % name)
    out = [unescape_c(sm.group(1)) for sm in re.finditer(r'str_lit\("((?:[^"\\]|\\.)*)"\)', m.group(1))]
    if len(out) != len(ARCHS):
        raise SystemExit("gen_microarch: %s has %d entries, expected %d (arch enum changed?)"
                         % (name, len(out), len(ARCHS)))
    return out


def parse_int_array(name, blk):
    m = re.search(r"gb_global int " + name + r"\[TargetArch_COUNT\]\s*=\s*\{(.*?)\n\};", blk, re.S)
    if not m:
        raise SystemExit("gen_microarch: %s not found in the selected block" % name)
    body = re.sub(r"//[^\n]*", "", m.group(1))
    out = [int(x) for x in re.findall(r"-?\d+", body)]
    if len(out) != len(ARCHS):
        raise SystemExit("gen_microarch: %s has %d entries, expected %d" % (name, len(out), len(ARCHS)))
    return out


def parse_pairs(blk):
    m = re.search(r"gb_global MicroarchFeatureList microarch_features_list\[\]\s*=\s*\{(.*?)\n\};",
                  blk, re.S)
    if not m:
        raise SystemExit("gen_microarch: microarch_features_list not found in the selected block")
    pairs = []
    for sm in re.finditer(r'\{\s*str_lit\("((?:[^"\\]|\\.)*)"\)\s*,\s*str_lit\("((?:[^"\\]|\\.)*)"\)\s*\}',
                          m.group(1)):
        pairs.append((unescape_c(sm.group(1)), unescape_c(sm.group(2))))
    return pairs


def odin_str(s):
    # These are LLVM feature names and CPU names: ASCII, no quotes, no backslashes. Assert rather than
    # silently emit something that would not compile.
    if '"' in s or "\\" in s:
        raise SystemExit("gen_microarch: unexpected quote/backslash in %r" % s)
    return '"%s"' % s


def emit(major, branch, ualist, feats, counts, pairs):
    total = sum(counts)
    if total != len(pairs):
        raise SystemExit("gen_microarch: counts sum to %d but microarch_features_list has %d entries -- "
                         "the offset walk would be WRONG, refusing to emit" % (total, len(pairs)))

    L = []
    L.append("// GENERATED FILE -- DO NOT EDIT BY HAND.")
    L.append("//")
    L.append("// Regenerate with:  python3 .claude/tools/gen_microarch.py")
    L.append("// Source of truth:  src/build_settings_microarch.cpp, the "
             "`%s` branch (LLVM_VERSION_MAJOR)." % branch)
    L.append("//")
    L.append("// #612: this data was hand-maintained and drifted TWICE -- microarch_default_features")
    L.append("// ignored the target arch entirely (returning x86-64 features for wasm/arm/riscv), and")
    L.append("// target_features_list was stale against LLVM 22 in BOTH directions on all seven arches.")
    L.append("// Deriving it from the C++ file the ORACLE compiles is what makes parity meaningful: a")
    L.append("// separate LLVM query could drift from the checked-in table the oracle actually carries.")
    L.append("//")
    L.append("// CAVEAT, deliberately visible. src/build_settings_microarch.cpp holds four tables behind")
    L.append("// #if LLVM_VERSION_MAJOR >= 22 / == 21 / == 20 / #else, and they genuinely differ (arm64")
    L.append("// has 98/91/82/69 microarchs respectively). The port has no LLVM dependency, so it cannot")
    L.append("// know which the oracle was built with. MICROARCH_LLVM_MAJOR below records the assumption")
    L.append("// this file was generated under. If the oracle is rebuilt against another LLVM, re-run the")
    L.append("// generator -- the stamp is what keeps that from being a silent divergence.")
    L.append("package checker")
    L.append("")
    L.append("// The LLVM major version whose table this file was generated from.")
    L.append("MICROARCH_LLVM_MAJOR :: %d" % major)
    L.append("")
    L.append("// C++: build_settings.cpp MicroarchFeatureList:130-133")
    L.append("Microarch_Feature_List :: struct {")
    L.append("\tmicroarch: string,")
    L.append("\tfeatures:  string,")
    L.append("}")
    L.append("")

    L.append("// C++: build_settings_microarch.cpp target_microarch_list -- the valid -microarch names")
    L.append("// per architecture, as a comma-separated list.")
    L.append("target_microarch_list := [Target_Arch_Kind]string {")
    for a, v in zip(ARCHS, ualist):
        L.append("\t.%-9s = %s," % (a, odin_str(v)))
    L.append("}")
    L.append("")

    L.append("// C++: build_settings_microarch.cpp target_features_list -- every feature name LLVM")
    L.append("// accepts for the architecture. This is the VALIDATION set for -target-features and")
    L.append("// @(enable_target_feature)/@(require_target_feature); being stale here over- AND")
    L.append("// under-rejects at once, which is exactly what #612 found.")
    L.append("target_features_list := [Target_Arch_Kind]string {")
    for a, v in zip(ARCHS, feats):
        L.append("\t.%-9s = %s," % (a, odin_str(v)))
    L.append("}")
    L.append("")

    L.append("// C++: build_settings_microarch.cpp target_microarch_counts -- how many entries of")
    L.append("// microarch_features_list belong to each arch. The entries are stored FLAT and sliced by a")
    L.append("// running offset, so these counts are load-bearing, not documentation.")
    L.append("target_microarch_counts := [Target_Arch_Kind]int {")
    for a, v in zip(ARCHS, counts):
        L.append("\t.%-9s = %d," % (a, v))
    L.append("}")
    L.append("")

    L.append("// C++: build_settings_microarch.cpp microarch_features_list -- flat, arch-major, in the")
    L.append("// same order as Target_Arch_Kind. Index it through microarch_features_for_arch, never")
    L.append("// directly by name: two arches can both define `generic` with different features, and")
    L.append("// matching by name alone is the #612 defect.")
    L.append("microarch_features_list := []Microarch_Feature_List {")
    off = 0
    for i, a in enumerate(ARCHS):
        n = counts[i]
        if n == 0:
            continue
        L.append("\t// %s:" % a)
        for name, fv in pairs[off:off + n]:
            L.append("\t{ %s, %s }," % (odin_str(name), odin_str(fv)))
        off += n
    L.append("}")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--llvm-major", type=int, default=None)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("-o", dest="out", default=OUT)
    args = ap.parse_args()

    major = args.llvm_major or detect_llvm_major()
    if major is None:
        raise SystemExit("gen_microarch: could not detect LLVM major; pass --llvm-major N explicitly "
                         "rather than letting the generator guess")

    text = open(CPP).read()
    blk, branch = select_block(text, major)
    ualist = parse_string_array("target_microarch_list", blk)
    feats = parse_string_array("target_features_list", blk)
    counts = parse_int_array("target_microarch_counts", blk)
    pairs = parse_pairs(blk)
    content = emit(major, branch, ualist, feats, counts, pairs)

    print("gen_microarch: LLVM major %d -> branch `%s`" % (major, branch))
    print("  microarchs per arch: %s" % ", ".join("%s=%d" % (a, c) for a, c in zip(ARCHS, counts) if c))
    print("  microarch_features_list entries: %d (counts sum matches)" % len(pairs))

    if args.check:
        if not os.path.exists(args.out):
            print("GEN-MICROARCH-STALE: %s does not exist" % args.out)
            return 1
        cur = open(args.out).read()
        if cur != content:
            print("GEN-MICROARCH-STALE: %s differs from what the C++ table would generate" % args.out)
            return 1
        print("GEN-MICROARCH-OK: generated file matches src/build_settings_microarch.cpp")
        return 0

    open(args.out, "w").write(content)
    print("  wrote %s (%d bytes)" % (args.out, len(content)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
